FROM registry.fedoraproject.org/fedora:27

RUN dnf install -y python3 python2 python-pip fedpkg git \
    python3-pytest make

ENV HOME=/usr/src/app

RUN mkdir -p ${HOME} && \
	useradd -u 1001 -r -g 0 -d ${HOME} -s /sbin/nologin \
    -c "Default Application User" default

WORKDIR ${HOME}

COPY . ${HOME}

RUN pip3 install -r requirements.txt -r tests/requirements.txt && \
    pip2 install wheel && \
    chown -R 1001:0 ${HOME}

USER 1001

RUN git config --global user.email "jdoe@example.com" && \
    git config --global user.name "John Doe"

CMD make test
