FROM registry.fedoraproject.org/fedora:28

RUN dnf install -y python2-pip fedpkg git make

ENV HOME=/usr/src/app \
    PYTHONDONTWRITEBYTECODE=1

RUN mkdir -p ${HOME} && \
    useradd -u 1001 -r -g 0 -d ${HOME} -s /sbin/nologin \
    -c "Default Application User" default

WORKDIR ${HOME}

COPY requirements.txt ${HOME}/
COPY tests/requirements.txt ${HOME}/tests/
RUN pip3 install -r requirements.txt -r tests/requirements.txt && \
    pip2 install wheel

COPY . ${HOME}
RUN chown -R 1001:0 ${HOME}

USER 1001

RUN git config --global user.email "jdoe@example.com" && \
    git config --global user.name "John Doe"

CMD make test
